title: FioriConf
url: "https://www.fioriconf.org"
author : Tobias Hofmann
description: |
  FioriConf is an online, free, live conference for Fiori Users
  The event will take place in 2024
enforce_ssl: "www.fioriconf.org"
relative_permalinks: false
permalink: news/:title/  # permalink: date
timezone: Europe/Berlin
conf_year: 2024
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

include:
  - _pages

# Build settings
markdown: kramdown

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

exclude:
- "*.yaml"
- "*.yml"
- .cache
- .editorconfig
- .gitignore
- .vendor
- bin
- bower_components
- CNAME
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docker-compose.yml
- EDITORS_GUIDE.md
- Gemfile
- Gemfile.lock
- justfile
- LICENSE
- Makefile
- node_modules
- NOTES.md
- package*.json
- Procfile
- README.md
- requirements.in
- vendor
- webpack.config.js

# We need `future` to allow our schedule to work :/
future: true

collections:  # process the _data folder
  components:
    output: false
  schedule:
    output: true
    permalink: /:collection/:name/
  organizers:
    output: false
    permalink: /:collection/
  presenters:
    output: true
    permalink: /:collection/

# SEO Plugin settings

twitter:
  username: fioriconf

# This is the default logo that people see with opengraph
logo: /static/img/logo-header.png


# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/img/logo-header.png
  - scope:
      path: "_presenters"
      type: presenters
    values:
      sitemap: false

# FioriConf email
conduct_email: "fioriconf@gmail.com"
contact_us_email: "fioriconf@gmail.com"
opportunity_grants_email: "fioriconf@gmail.com"
program_team_email: "fioriconf@gmail.com"
sponsors_email: "fioriconf@gmail.com"

# Our FioriConf links
cfp_application: "https://www.eventbrite.com"
slack_link: ""
sponsorship_prospectus: ""
ticket_link: "https://www.eventbrite.com"
youtube_link: "https://www.youtube.com/@fioriconf"

github: [metadata]

